import Head from 'next/head'
import colors from '../data/colors.json'
import Link from 'next/link';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Color Pages</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {colors.map((color) => (<Link href={`/${color.name}`}>
      <h2>{color.name}</h2>
      </Link>))}
    </div>
  )
}
